### ISSUE TITLE
Github Build Action: Restore Database Only When XML Files Involved

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#3939]
## Feature request
Right now, the Github Action _ADempiere Build_ defined in file _main.yml_, starts the build process:
![imagen](https://user-images.githubusercontent.com/1789408/177221847-cb9e0ccf-619d-432f-8c33-6c89f479d957.png)

The _build.xml_ file located directly at the root of the adempiere repository has a target called _build,_ which is executed by the `ant build` call.

The following is then executed:
- Building ADempiere
- Deploy Adempiere (Preparation for setup)
- SilentSetup
- Run Import Adempiere
- Run DB Restore Adempiere (this ought to be skipped by accepting PR https://github.com/adempiere/adempiere/pull/3935)
- Run Migrate XML
- Run Export Database

This means that whatever happens **the database is always restored**, including executing all XMLs starting from seed.
This solution has two disadvantages: it takes a long time for the action to finish and also it consumes time and resources Github allocates to our project.

#### Describe the solution you'd like
The first step would be to separate at least the building and installation of Adempiere from the database import, restore, and export using the present tools (ANT + build.xml files).

#### Describe alternatives you've considered
The best solution would be to implement everything in _Gradle_ but it would take too long. Modifying the present solution may be less complex/complicated.
It would also be less invasive and easier to test.
The solution must be also backward-compatible, i.e. it must work as it does today.

#### Additional context
Here are some implementation thoughts, in steps.
The implementation may differ due to syntax and other reasons, but the main idea should be conveyed:

1.- Divide file _adempiere/build.xml_ into several targets
```
<target name="build" depends="xxxx, yyyy, zzzz", ...> 
        <property name="dbrestore" value="true"/>

```

The additional targets (in the example xxxx, yyyy, zzzz) would be 
- Building ADempiere
- Deploy Adempiere
- SilentSetup
- Run Import Adempiere
- Run DB Restore Adempiere
- Run Migrate XML
- Run Export Database

2.- Still in _adempiere/build.xml_, make all database targets dependent on a property, for example _dbrestore_:
```
<target name="run-import-adempiere" description="Run Import Adempiere"
    if="${dbrestore.set}">
    :
    :
</target>

```

3.- Modifications in Github Action file _main.yaml_
The following calls must be possible:
- ant build
- ant -Ddbrestore.set=true build
- ant -Ddbrestore.set=false build
    
4.- Convert the present yaml file _main.yaml_ into a local action, deployed under _.github/actions_.
The name of this action could be _admpiere-build_.
This action would do basically the same as the present action _ADempiere Bild_, implemented in file _main.yml_.
This action gets an input parameter: _dbrestore_ which can be (true || false)
If input parameter dbrestore==true , ANT will be called as follows: `ant -Ddbrestore.set=true build`
If input parameter dbrestore==false , ANT will be called as follows:  `ant -Ddbrestore.set=false build` or `ant build`.
    
5.- Replace the present _main.yaml_ file with two yaml files, each with different purposes:
**yaml file 1**: it is triggered only when XML files are pushed (dbrestore= true). Note the `paths` keyword:
```
        on:
          # Triggers the workflow on push or pull request events
          push:
            branches: [ "master", "develop", "bugfix/*", "feature/*" ]
            paths: 
              - 'migration/392lts-393lts/**.xml'
          pull_request:
            branches: [ "master", "develop", "bugfix/*", "feature/*" ]
            paths: 
              - 'migration/393lts-394lts/**.xml'
        :
        :
        - uses: ../actions/adempiere-build
            with:
              dbrestore= true
```    
**yaml file 2**: it is triggered only when no XML files are pushed (dbrestore= false):
```

        on:
          # Triggers the workflow on push or pull request events
          push:
            branches: [ "master", "develop", "bugfix/*", "feature/*" ]
          pull_request:
            branches: [ "master", "develop", "bugfix/*", "feature/*" ]
        :
        :
        - uses: ../actions/adempiere-build
            with:
              dbrestore= false
```

Comments and observations welcome!
