### ISSUE TITLE
Add Files Whose Modification Triggers Seed Generation

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#4012]
## Feature request
Regarding the pull request about generating a seed only when needed (https://github.com/adempiere/adempiere/pull/3972)  @EdwinBetanc0urt  suggested the inclusion of additional files. (See  [****](https://github.com/adempiere/adempiere/pull/3972#issuecomment-1217379515) ).

It seems a sensible feature.

#### Describe the solution you'd like
I'd change the GitHub Actions file **.github/workfolws/main.yml**:
```

      # Filter files to discern whether to run with or without database restore 
      - name: Discern which files changed ...
        uses: dorny/paths-filter@v2
        id: changed-files
        with:
          filters: |
            xml-files:
              - 'migration/**/*.xml'
```

I would try to add more filters for 
- build.xml, and the 
- .sh/.bat files concerning database migration/restore

I will not push any commits right now, because there are two pull requests pending; and I will wait for their acceptance before continuing with this feature reaquest.
