### ISSUE TITLE
Translate Contributions in the Discussions Section into English

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#4138]
## Feature request
Translate comments of Discussions into English.
For example, in the Discussion section of this repository, the discussion was started in Spanish, but some participants wish to get it in English (see https://github.com/adempiere/adempiere/discussions/4123).

#### Describe the solution you'd like
The solution would be to include discussions in the responsible GitHub Event Action. 
The file concerned would be the following: https://github.com/adempiere/adempiere/blob/develop/.github/workflows/issue-and-pr-translator.yml .

According to GitHub official documentation about events (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#discussion), the solution would be to add the following code:

```
on:
  ...
  discussion:
    types: [created, edited, answered]
  discussion_comment:
    types: [created, deleted]
  ...
```
